% Depending on whether 'Hints (Tooltips)' is selected in the 'Options' menu
% this does or does not set the short hints (tooltip strings) that are displayed
% when the mouse hovers above an element of the spike train generator (STG).

if f_para.hints==1
    set(STG_num_trains_edit,'TooltipString',sprintf('This will generate the desired number of empty spike trains (integer value).'))
    set(STG_num_trains_text,'TooltipString',get(STG_num_trains_edit,'TooltipString'))
    set(STG_tmin_edit,'TooltipString',sprintf('Beginning of the recording/simulation.'))
    set(STG_tmin_text,'TooltipString',get(STG_tmin_edit,'TooltipString'))
    set(STG_tmax_edit,'TooltipString',sprintf('End of the recording/simulation.'))
    set(STG_tmax_text,'TooltipString',get(STG_tmax_edit,'TooltipString'))
    set(STG_dts_edit,'TooltipString',sprintf('Defines the temporal resolution of the recording/simulation.'))
    set(STG_dts_text,'TooltipString',get(STG_dts_edit,'TooltipString'))
    set(STG_Init_Cancel_pushbutton,'TooltipString',sprintf('Brings you back to SPIKY.'))
    set(STG_Init_OK_pushbutton,'TooltipString',sprintf('Accepts selected parameters and allows you to start generating spike trains.'))
    
    set(STG_Final_Cancel_pushbutton,'TooltipString',sprintf('This brings you back to the main parameters panel.\n To go immediately back to SPIKY, simply close the STG window (x in upper right corner).'))
    set(STG_Final_Reset_pushbutton,'TooltipString',sprintf('This deletes all generated spikes and allows you to start again.\n The main parameters selected initially remain valid.\n In order to change these, press Cancel next.'))
    set(STG_Final_OK_pushbutton,'TooltipString',sprintf('This saves all spikes and redirects you to SPIKY where you can proceed with the analysis.'))
    set(STG_Options_OK_pushbutton,'TooltipString',sprintf('This generates the selected predefined spike train patterns for the selected spike trains and the selected time intervals.'))
    set(STG_wmin_edit,'TooltipString',sprintf('Defines the beginning of the subinterval in which the spike train patterns will be generated.'))
    set(STG_wmin_text,'TooltipString',get(STG_wmin_edit,'TooltipString'))
    set(STG_wmax_edit,'TooltipString',sprintf('Defines the end of the subinterval in which the spike train patterns will be generated.'))
    set(STG_wmax_text,'TooltipString',get(STG_wmax_edit,'TooltipString'))
    set(STG_spike_train_selection_panel,'TooltipString',sprintf('This allows you to choose if you would like the selected spike train patterns to appear in all (default) or only in selected spike trains or spike train groups (which you should define at the bottom of this panel).'))
    set(STG_select_train_mode_popupmenu,'TooltipString',get(STG_spike_train_selection_panel,'TooltipString'))
    set(STG_trains_edit,'TooltipString',sprintf('If Select trains is selected, you can either identify the spike trains directly using Matlab notation or use the bottom below and select them from a list.'))
    set(STG_trains_text,'TooltipString',get(STG_trains_edit,'TooltipString'))
    set(STG_train_groups_edit,'TooltipString',sprintf('If Select groups is selected, you can either identify the spike train groups directly using Matlab notation or use the bottom below and select them from a list.'))
    set(STG_train_groups_text,'TooltipString',get(STG_train_groups_edit,'TooltipString'))
    set(STG_trains_pushbutton,'TooltipString',sprintf('This allows you to select the spike trains you would like to modify from a list.'))
    set(STG_train_groups_pushbutton,'TooltipString',sprintf('This allows you to select the spike train groups you would like to modify from a list.'))
    set(STG_group_names_edit,'TooltipString',sprintf('Before you can select spike train groups you should define them here.\n Identify their names each separated by ; and a space and ending with a ;, e.g. G1; G2; G3; G4;.'))
    set(STG_group_names_text,'TooltipString',get(STG_group_names_edit,'TooltipString'))
    set(STG_group_sizes_edit,'TooltipString',sprintf('Then identify their sizes using Matlab notation, e.g. 10 10 10 10.'))
    set(STG_group_sizes_text,'TooltipString',get(STG_group_sizes_edit,'TooltipString'))
    set(STG_periodic_radiobutton,'TooltipString',sprintf('This will generate identical periodic spike trains in the selected time interval for the selected spike trains.'))
    set(STG_splay_radiobutton,'TooltipString',sprintf('This will generate asynchronous spike trains (one of n! possible) in the selected time interval for the selected spike trains.'))
    set(STG_uniform_radiobutton,'TooltipString',sprintf('This will generate spike trains with uniform distribution in the selected time interval for the selected spike trains.'))
    set(STG_poisson_radiobutton,'TooltipString',sprintf('This will generate Poisson spike trains in the selected time interval for the selected spike trains.'))
    set(STG_periodic_rate_edit,'TooltipString',sprintf('Select the firing rate of the (individual) identical periodic spike trains.'))
    set(STG_splay_rate_edit,'TooltipString',sprintf('Select the firing rate of the (individual) splay spike trains.'))
    set(STG_uniform_rate_edit,'TooltipString',sprintf('Select the firing rate of the (individual) uniform spike trains.'))
    set(STG_poisson_rate_edit,'TooltipString',sprintf('Select the firing rate of the (individual) Poisson spike trains.'))
    set(STG_periodic_jitter_edit,'TooltipString',sprintf('This will add jitter to the identical periodic spike trains.'))
    set(STG_splay_jitter_edit,'TooltipString',sprintf('This will add jitter to the splay spike trains.'))
    set(STG_add_radiobutton,'TooltipString',sprintf('By activating this mode all newly generated spike train patterns will be added to the existing spikes in the selected time interval and selected spike trains.'))
    set(STG_replace_radiobutton,'TooltipString',sprintf('By activating this mode the existing spike trains occupying the selected time interval and selected spike trains will (first be deleted and then) be replaced by the newly generated spike train patterns.'))
else
    set(STG_num_trains_text,'TooltipString','')
    set(STG_num_trains_edit,'TooltipString','')
    set(STG_tmin_text,'TooltipString','')
    set(STG_tmin_edit,'TooltipString','')
    set(STG_tmax_text,'TooltipString','')
    set(STG_tmax_edit,'TooltipString','')
    set(STG_dts_text,'TooltipString','')
    set(STG_dts_edit,'TooltipString','')
    set(STG_Init_Cancel_pushbutton,'TooltipString','')
    set(STG_Init_OK_pushbutton,'TooltipString','')
    
    set(STG_Final_Cancel_pushbutton,'TooltipString','')
    set(STG_Final_Reset_pushbutton,'TooltipString','')
    set(STG_Final_OK_pushbutton,'TooltipString','')
    set(STG_Options_OK_pushbutton,'TooltipString','')
    set(STG_wmin_text,'TooltipString','')
    set(STG_wmin_edit,'TooltipString','')
    set(STG_wmax_text,'TooltipString','')
    set(STG_wmax_edit,'TooltipString','')
    set(STG_spike_train_selection_panel,'TooltipString','')
    set(STG_select_train_mode_popupmenu,'TooltipString','')
    set(STG_trains_text,'TooltipString','')
    set(STG_trains_edit,'TooltipString','')
    set(STG_train_groups_text,'TooltipString','')
    set(STG_train_groups_edit,'TooltipString','')
    set(STG_trains_pushbutton,'TooltipString','')
    set(STG_train_groups_pushbutton,'TooltipString','')
    set(STG_group_names_text,'TooltipString','')
    set(STG_group_names_edit,'TooltipString','')
    set(STG_group_sizes_text,'TooltipString','')
    set(STG_group_sizes_edit,'TooltipString','')
    set(STG_periodic_radiobutton,'TooltipString','')
    set(STG_splay_radiobutton,'TooltipString','')
    set(STG_uniform_radiobutton,'TooltipString','')
    set(STG_poisson_radiobutton,'TooltipString','')
    set(STG_periodic_rate_edit,'TooltipString','')
    set(STG_splay_rate_edit,'TooltipString','')
    set(STG_uniform_rate_edit,'TooltipString','')
    set(STG_poisson_rate_edit,'TooltipString','')
    set(STG_periodic_jitter_edit,'TooltipString','')
    set(STG_splay_jitter_edit,'TooltipString','')
    set(STG_add_radiobutton,'TooltipString','')
    set(STG_replace_radiobutton,'TooltipString','')
end
