
default: subdirs csim.dll

subdirs:
	cd src
	nmake -f Makefile.win
	cd ..

csim.dll: src\csim.dll
	copy src\csim.dll csim.dll

mrproper:
	cd src
	nmake -f Makefile.win mrproper
	cd ..
	del /Q csim.*

clean:
	cd src
	nmake -f Makefile.win clean
	cd ..
	del /Q csim.*

distclean:
	cd src
	nmake -f Makefile.win distclean
	cd ..
	del /Q demos\*.mat
